apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user = guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: rabbitmq
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: rabbitmq
#   template:
#     metadata:
#       labels:
#         app: rabbitmq
#     spec:
#       containers:
#         - name: rabbitmq
#           image: rabbitmq:3-management
#           env:
#             - name: RABBITMQ_DEFAULT_USER
#               value: "guest"
#             - name: RABBITMQ_DEFAULT_PASS
#               value: "guest"
#           ports:
#             - containerPort: 5672
#             - containerPort: 15672
#           readinessProbe:
#             exec:
#               command: ["rabbitmqctl", "status"]
#             initialDelaySeconds: 10
#             periodSeconds: 10
#           livenessProbe:
#             exec:
#               command: ["rabbitmqctl", "status"]
#             initialDelaySeconds: 30
#             periodSeconds: 10

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq
# spec:
#   ports:
#     - name: amqp
#       port: 5672
#       targetPort: 5672
#     - name: management
#       port: 15672
#       targetPort: 15672
#   selector:
#     app: rabbitmq
