apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: task-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "pass"
            - name: DB_HOST
              value: "db"
            - name: DB_NAME
              value: "tasks"
            - name: DB_PORT
              value: "3306"
            - name: PORT
              value: "8080"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"

---
apiVersion: v1
kind: Service
metadata:
  name: task-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: task-api
